version: "3.6"
services:
    rabbitmq:
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_NODENAME=rabbitmq
        image: rabbitmq:3-management
        
    acquiringbankmock:
        container_name: acquiringbankmock
        ports:
            - 80
            - 44379:44379
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:44379;http://+
            - ASPNETCORE_HTTPS_PORT=44379
            - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - Kestrel__Certificates__Default__Password=Password
        volumes:
            - ~/.aspnet/https:/https:ro
        build:
            context: ./AcquiringBankMock
            dockerfile: AcquiringBankMock/Dockerfile
        restart: on-failure
                
    paymentapi:
        container_name: paymentapi
        ports:
            - 44384:44384
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:44384;http://+
            - ASPNETCORE_HTTPS_PORT=44384
            - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - Kestrel__Certificates__Default__Password=Password
            # RabbitMq Settings
            - RabbitMq__Hostname=rabbitmq
            - RabbitMq__QueueName=PaymentQueue
            - RabbitMq__UserName=user
            - RabbitMq__Password=password
            # External Bank EndPoint
            - ExternalBankHook__EndPoint=https://acquiringbankmock:44379/ProcessPayment/
        volumes:
            - ~/.aspnet/https:/https:ro
        build:
            context: ./PaymentApi
            dockerfile: PaymentApi/Dockerfile
        restart: on-failure        
        depends_on:
            - rabbitmq
        
    paymentgatewayapi:
        container_name: paymentgatewayapi
        ports:
            - 80
            - 44344:44344
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:44344;http://+
            - ASPNETCORE_HTTPS_PORT=44344
            - Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
            - Kestrel__Certificates__Default__Password=Password
            # RabbitMq Settings
            - RabbitMq__Hostname=rabbitmq
            - RabbitMq__QueueName=PaymentQueue
            - RabbitMq__UserName=user
            - RabbitMq__Password=password
        volumes:
            - ~/.aspnet/https:/https:ro
        build:
            context: ./PaymentGatewayApi
            dockerfile: PaymentGatewayApi/Dockerfile     
        restart: on-failure
        depends_on:
            - rabbitmq