name: .NET Core CI/CD

on:
  push:
    branches: 
      - master
    paths:
      - "**"
      - "!**.md"
      - "**/*"
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "**/*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ~/paymentgateway/PaymentApi/PaymentApi.sln --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
